package Modelo.Entidad;
// Generated 10/10/2019 10:57:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Presentacion generated by hbm2java
 */
public class Presentacion  implements java.io.Serializable {


     private int idPresentacion;
     private String descripcion;
     private Set productos = new HashSet(0);

    public Presentacion() {
    }

	
    public Presentacion(int idPresentacion, String descripcion) {
        this.idPresentacion = idPresentacion;
        this.descripcion = descripcion;
    }
    public Presentacion(int idPresentacion, String descripcion, Set productos) {
       this.idPresentacion = idPresentacion;
       this.descripcion = descripcion;
       this.productos = productos;
    }
   
    public int getIdPresentacion() {
        return this.idPresentacion;
    }
    
    public void setIdPresentacion(int idPresentacion) {
        this.idPresentacion = idPresentacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


